"use client";

import { useState, useMemo } from "react";
import { 
  FileUp, 
  ArrowRight, 
  CheckCircle2, 
  AlertCircle, 
  RefreshCcw, 
  Download,
  Search,
  Check,
  X,
  Plus,
  AlertTriangle
} from "lucide-react";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { apps, type CatalogItem } from "@/data/apps";
import { cn } from "@/lib/utils";

interface AuditRow {
  name: string;
  localPath?: string;
  repoUrl?: string;
  lastTouched?: string;
  status?: string;
  [key: string]: any;
}

interface MatchResult {
  row: AuditRow;
  match?: CatalogItem;
  matchType: "exact-name" | "fuzzy-name" | "path" | "repo" | "none";
  conflicts: string[];
}

export function CSVImportPreview() {
  const [data, setData] = useState<AuditRow[]>([]);
  const [fileName, setFileName] = useState<string | null>(null);

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setFileName(file.name);
    const reader = new FileReader();
    reader.onload = (event) => {
      const text = event.target?.result as string;
      // Simple CSV parser
      const lines = text.split(/\r?\n/);
      const headers = lines[0].split(",").map(h => h.trim().replace(/^"|"$/g, ""));
      
      const parsedData = lines.slice(1).filter(line => line.trim()).map(line => {
        const values = line.split(",").map(v => v.trim().replace(/^"|"$/g, ""));
        const row: any = {};
        headers.forEach((header, i) => {
          row[header] = values[i];
        });
        return row as AuditRow;
      });

      setData(parsedData);
    };
    reader.readAsText(file);
  };

  const matches = useMemo(() => {
    return data.map(row => {
      let match: CatalogItem | undefined;
      let matchType: MatchResult["matchType"] = "none";
      const conflicts: string[] = [];

      // Try exact name match
      match = apps.find(a => a.name.toLowerCase() === row.name.toLowerCase());
      if (match) {
        matchType = "exact-name";
      } else {
        // Try path match
        match = apps.find(a => a.localPath === row.localPath);
        if (match) matchType = "path";
        else {
          // Try repo match
          match = apps.find(a => a.repoUrl === row.repoUrl);
          if (match) matchType = "repo";
        }
      }

      if (match) {
        // Check for conflicts
        if (row.repoUrl && match.repoUrl && row.repoUrl !== match.repoUrl) conflicts.push("repoUrl");
        if (row.localPath && match.localPath && row.localPath !== match.localPath) conflicts.push("localPath");
      }

      return { row, match, matchType, conflicts };
    });
  }, [data]);

  const stats = useMemo(() => {
    return {
      total: matches.length,
      new: matches.filter(m => m.matchType === "none").length,
      matched: matches.filter(m => m.matchType !== "none").length,
      conflicts: matches.filter(m => m.conflicts.length > 0).length,
    };
  }, [matches]);

  if (data.length === 0) {
    return (
      <Card className="border-dashed border-2">
        <CardContent className="flex flex-col items-center justify-center py-12 space-y-4">
          <div className="p-4 bg-muted rounded-full">
            <FileUp className="h-8 w-8 text-muted-foreground" />
          </div>
          <div className="text-center">
            <h3 className="text-lg font-medium">Upload Project Audit CSV</h3>
            <p className="text-sm text-muted-foreground">Select the CSV file generated by the Copilot audit</p>
          </div>
          <Input 
            type="file" 
            accept=".csv" 
            className="hidden" 
            id="csv-upload" 
            onChange={handleFileUpload}
          />
          <Button asChild>
            <label htmlFor="csv-upload" className="cursor-pointer">Select File</label>
          </Button>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <div>
          <h2 className="text-2xl font-bold flex items-center gap-2">
            Import Preview: {fileName}
            <Button variant="ghost" size="sm" onClick={() => { setData([]); setFileName(null); }}>
              <RefreshCcw className="h-4 w-4" />
            </Button>
          </h2>
          <p className="text-muted-foreground">Comparing audit data with existing JoshHub inventory</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline" className="gap-2">
            <Download className="h-4 w-4" /> Export Merged JSON
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card>
          <CardHeader className="py-3 px-4">
            <CardTitle className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Total Rows</CardTitle>
          </CardHeader>
          <CardContent className="py-0 px-4 pb-4">
            <div className="text-2xl font-bold">{stats.total}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="py-3 px-4">
            <CardTitle className="text-xs font-medium text-emerald-600 uppercase tracking-wider">Matches</CardTitle>
          </CardHeader>
          <CardContent className="py-0 px-4 pb-4">
            <div className="text-2xl font-bold text-emerald-700">{stats.matched}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="py-3 px-4">
            <CardTitle className="text-xs font-medium text-blue-600 uppercase tracking-wider">New Projects</CardTitle>
          </CardHeader>
          <CardContent className="py-0 px-4 pb-4">
            <div className="text-2xl font-bold text-blue-700">{stats.new}</div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="py-3 px-4">
            <CardTitle className="text-xs font-medium text-rose-600 uppercase tracking-wider">Conflicts</CardTitle>
          </CardHeader>
          <CardContent className="py-0 px-4 pb-4">
            <div className="text-2xl font-bold text-rose-700">{stats.conflicts}</div>
          </CardContent>
        </Card>
      </div>

      <div className="border rounded-lg overflow-hidden">
        <table className="w-full text-sm">
          <thead className="bg-muted/50 border-b">
            <tr>
              <th className="px-4 py-3 text-left font-medium">Audit Entry</th>
              <th className="px-4 py-3 text-center w-16">Match</th>
              <th className="px-4 py-3 text-left font-medium">JoshHub Project</th>
              <th className="px-4 py-3 text-left font-medium">Action</th>
            </tr>
          </thead>
          <tbody className="divide-y">
            {matches.map((m, i) => (
              <tr key={i} className={cn(m.conflicts.length > 0 && "bg-rose-50/50 dark:bg-rose-950/10")}>
                <td className="px-4 py-4">
                  <div className="font-semibold">{m.row.name}</div>
                  <div className="text-xs text-muted-foreground font-mono mt-1">{m.row.localPath || "No path"}</div>
                </td>
                <td className="px-4 py-4 text-center">
                  {m.match ? (
                    <div className="flex flex-col items-center gap-1">
                      <ArrowRight className="h-4 w-4 text-emerald-500" />
                      <Badge variant="outline" className="text-[10px] py-0">{m.matchType}</Badge>
                    </div>
                  ) : (
                    <Plus className="h-4 w-4 text-blue-500 mx-auto" />
                  )}
                </td>
                <td className="px-4 py-4">
                  {m.match ? (
                    <div>
                      <div className="font-semibold flex items-center gap-2">
                        {m.match.name}
                        {m.conflicts.length > 0 && <AlertTriangle className="h-3 w-3 text-rose-500" />}
                      </div>
                      <div className="text-xs text-muted-foreground font-mono mt-1">{m.match.localPath || "No path"}</div>
                      {m.conflicts.map(c => (
                        <div key={c} className="text-[10px] text-rose-600 mt-1 font-medium">Conflict: {c}</div>
                      ))}
                    </div>
                  ) : (
                    <div className="text-muted-foreground italic text-xs">New entry candidate</div>
                  )}
                </td>
                <td className="px-4 py-4">
                  {m.match ? (
                    <Badge variant="outline" className="bg-emerald-50 text-emerald-700 border-emerald-200">
                      Update metadata
                    </Badge>
                  ) : (
                    <Badge variant="outline" className="bg-blue-50 text-blue-700 border-blue-200">
                      Create project
                    </Badge>
                  )}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

function Input({ className, ...props }: React.InputHTMLAttributes<HTMLInputElement>) {
  return (
    <input
      className={cn(
        "flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
        className
      )}
      {...props}
    />
  );
}
